"""Se añaden firmas al usuario

Revision ID: 02619ed3ec78
Revises: 7beea29596d2
Create Date: 2026-07-28 12:13:41.132595

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02619ed3ec78"
down_revision: Union[str, Sequence[str], None] = "7beea29596d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usuarios", sa.Column("firma", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuarios", "firma")
    # ### end Alembic commands ###
