"""Se agrega un flag de consolidación en Expediente

Revision ID: 30b8a68bf496
Revises: 02619ed3ec78
Create Date: 2026-07-28 16:30:49.849081

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30b8a68bf496"
down_revision: Union[str, Sequence[str], None] = "02619ed3ec78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expedientes", sa.Column("fecha_consolidacion", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expedientes", "fecha_consolidacion")
    # ### end Alembic commands ###
