"""Se agregan campos para recuperación de contraseña

Revision ID: 473c8b62814b
Revises: 33df6626b2d3
Create Date: 2026-08-25 09:06:41.865255

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "473c8b62814b"
down_revision: Union[str, Sequence[str], None] = "33df6626b2d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usuarios",
        sa.Column("codigo_recuperacion_hash", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "usuarios",
        sa.Column(
            "codigo_recuperacion_expira", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuarios", "codigo_recuperacion_expira")
    op.drop_column("usuarios", "codigo_recuperacion_hash")
    # ### end Alembic commands ###
