"""Se cambia la decision del cierre de expediente.

Revision ID: 7beea29596d2
Revises: e0b80b17277e
Create Date: 2026-07-27 17:03:15.954393

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7beea29596d2"
down_revision: Union[str, Sequence[str], None] = "e0b80b17277e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cobranzas", sa.Column("dia", sa.SmallInteger(), nullable=False))
    op.drop_constraint(op.f("uq_orden"), "cobranzas", type_="unique")
    op.create_unique_constraint(
        "uq_dia_orden", "cobranzas", ["id_expediente", "dia", "orden"]
    )
    op.drop_column("cobranzas", "resultado")
    op.add_column("expedientes", sa.Column("id_usuario", sa.Integer(), nullable=True))
    op.add_column(
        "expedientes",
        sa.Column("estado", sa.Boolean(), server_default="true", nullable=False),
    )
    op.create_foreign_key(
        None,
        "expedientes",
        "usuarios",
        ["id_usuario"],
        ["id_usuario"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "expedientes", type_="foreignkey")
    op.drop_column("expedientes", "estado")
    op.drop_column("expedientes", "id_usuario")
    op.add_column(
        "cobranzas",
        sa.Column(
            "resultado", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint("uq_dia_orden", "cobranzas", type_="unique")
    op.create_unique_constraint(
        op.f("uq_orden"),
        "cobranzas",
        ["id_expediente", "orden"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("cobranzas", "dia")
    # ### end Alembic commands ###
