"""Se añade monto vencido del expediente

Revision ID: 9fbf39d2ea47
Revises: 473c8b62814b
Create Date: 2026-08-26 09:50:56.080104

"""

from typing import Union
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fbf39d2ea47"
down_revision: Union[str, Sequence[str], None] = "473c8b62814b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expedientes",
        sa.Column("monto_vencido", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expedientes", "monto_vencido")
    # ### end Alembic commands ###
