"""Se añade día actual del expediente

Revision ID: bf4c31454609
Revises: 9fbf39d2ea47
Create Date: 2026-08-27 09:51:17.173850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4c31454609'
down_revision: Union[str, Sequence[str], None] = '9fbf39d2ea47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expedientes', sa.Column('dia_actual', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expedientes', 'dia_actual')
    # ### end Alembic commands ###
