"""se agregan comentarios a expediente y contacto a cobranza

Revision ID: c26eced01799
Revises: ee3f3e185587
Create Date: 2026-08-19 15:45:16.420030

"""

from typing import Union
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c26eced01799"
down_revision: Union[str, Sequence[str], None] = "ee3f3e185587"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cobranzas", sa.Column("contacto", sa.Boolean(), nullable=False))
    op.add_column("expedientes", sa.Column("comentarios", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expedientes", "comentarios")
    op.drop_column("cobranzas", "contacto")
    # ### end Alembic commands ###
