"""Se quita descripción del tipo de documento

Revision ID: d863058f612d
Revises: 8582b8693a03
Create Date: 2026-08-11 09:32:32.651942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd863058f612d'
down_revision: Union[str, Sequence[str], None] = '8582b8693a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_documento', 'descripcion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_documento', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
