"""Primera migración

Revision ID: db5e94cd8b74
Revises: 
Create Date: 2026-07-17 12:43:17.829116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5e94cd8b74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('interlocutor', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('interlocutor')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_documento',
    sa.Column('id_tipo_documento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_documento'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('expedientes',
    sa.Column('id_expediente', sa.Integer(), nullable=False),
    sa.Column('interlocutor', sa.String(length=20), nullable=False),
    sa.Column('fecha_incumplimiento', sa.Date(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interlocutor'], ['clientes.interlocutor'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_expediente')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('cobranzas',
    sa.Column('id_cobranza', sa.Integer(), nullable=False),
    sa.Column('id_expediente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('medio', sa.String(length=50), nullable=True),
    sa.Column('resultado', sa.String(length=100), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('orden BETWEEN 1 AND 3', name='chk_orden'),
    sa.ForeignKeyConstraint(['id_expediente'], ['expedientes.id_expediente'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_cobranza'),
    sa.UniqueConstraint('id_expediente', 'orden', name='uq_orden')
    )
    op.create_table('documentos',
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('id_expediente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=False),
    sa.Column('uuid_archivo', sa.Uuid(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_expediente'], ['expedientes.id_expediente'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tipo_documento'], ['tipos_documento.id_tipo_documento'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_documento'),
    sa.UniqueConstraint('uuid_archivo')
    )
    op.create_table('evidencias',
    sa.Column('id_evidencia', sa.Integer(), nullable=False),
    sa.Column('id_cobranza', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('uuid_archivo', sa.Uuid(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_cobranza'], ['cobranzas.id_cobranza'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_evidencia'),
    sa.UniqueConstraint('uuid_archivo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidencias')
    op.drop_table('documentos')
    op.drop_table('cobranzas')
    op.drop_table('usuarios')
    op.drop_table('expedientes')
    op.drop_table('tipos_documento')
    op.drop_table('roles')
    op.drop_table('clientes')
    # ### end Alembic commands ###
