"""Se quita descripcion de expediente, no se necesita

Revision ID: e0b80b17277e
Revises: db5e94cd8b74
Create Date: 2026-07-20 10:20:58.627232

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0b80b17277e"
down_revision: Union[str, Sequence[str], None] = "db5e94cd8b74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expedientes", "descripcion")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expedientes",
        sa.Column("descripcion", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
