"""Se modifica la tabla clientes, quitando telefono y agregando central y contrato

Revision ID: fcd1b7a3d5e5
Revises: 30b8a68bf496
Create Date: 2026-08-06 10:12:27.012089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fcd1b7a3d5e5"
down_revision: Union[str, Sequence[str], None] = "30b8a68bf496"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clientes", sa.Column("central", sa.String(length=10), nullable=False)
    )
    op.add_column(
        "clientes", sa.Column("contrato", sa.String(length=50), nullable=True)
    )
    op.drop_column("clientes", "telefono")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clientes",
        sa.Column(
            "telefono", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("clientes", "contrato")
    op.drop_column("clientes", "central")
    # ### end Alembic commands ###
